// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/profile/presentation/cubit/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:exam_app/features/profile/domain/entities/user_profile_entity.dart'
    as _i5;
import 'package:exam_app/features/profile/domain/repositories/profile_repository.dart'
    as _i2;
import 'package:exam_app/features/profile/domain/usecases/change_password_usecase.dart'
    as _i8;
import 'package:exam_app/features/profile/domain/usecases/edit_profile_usecase.dart'
    as _i6;
import 'package:exam_app/features/profile/domain/usecases/get_profile_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileRepository_0 extends _i1.SmartFake
    implements _i2.ProfileRepository {
  _FakeProfileRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i3.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProfileRepository);

  @override
  _i4.Future<_i5.UserProfileEntity?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.UserProfileEntity?>.value(),
          )
          as _i4.Future<_i5.UserProfileEntity?>);
}

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i6.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProfileRepository);

  @override
  _i4.Future<String> call({
    String? firstName,
    String? lastName,
    String? email,
    String? phone,
    String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phone: phone,
              #username: username,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#call, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #phone: phone,
                  #username: username,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i8.ChangePasswordUseCase {
  MockChangePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProfileRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProfileRepository);

  @override
  _i4.Future<String> call({
    required String? oldPassword,
    required String? newPassword,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#call, [], {
                  #oldPassword: oldPassword,
                  #newPassword: newPassword,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}
