// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/exams_page/data/repos/get_exam_questions_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:exam_app/core/config/base_response/base_response.dart' as _i3;
import 'package:exam_app/features/exams_page/api/api_client/exam_questions_api_client.dart'
    as _i2;
import 'package:exam_app/features/exams_page/api/datasources/get_exam_questions_remote_datasource_impl.dart'
    as _i4;
import 'package:exam_app/features/exams_page/data/models/question_dto.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExamQuestionsApiClient_0 extends _i1.SmartFake
    implements _i2.ExamQuestionsApiClient {
  _FakeExamQuestionsApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseResponse_1<T> extends _i1.SmartFake
    implements _i3.BaseResponse<T> {
  _FakeBaseResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetExamQuestionsRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExamQuestionsRemoteDatasourceImpl extends _i1.Mock
    implements _i4.GetExamQuestionsRemoteDatasourceImpl {
  MockGetExamQuestionsRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExamQuestionsApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeExamQuestionsApiClient_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.ExamQuestionsApiClient);

  @override
  set apiClient(_i2.ExamQuestionsApiClient? _apiClient) => super.noSuchMethod(
    Invocation.setter(#apiClient, _apiClient),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.BaseResponse<List<_i6.QuestionDto>>> getExamQuestions({
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExamQuestions, [], {#examId: examId}),
            returnValue:
                _i5.Future<_i3.BaseResponse<List<_i6.QuestionDto>>>.value(
                  _FakeBaseResponse_1<List<_i6.QuestionDto>>(
                    this,
                    Invocation.method(#getExamQuestions, [], {#examId: examId}),
                  ),
                ),
          )
          as _i5.Future<_i3.BaseResponse<List<_i6.QuestionDto>>>);
}
