// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/exams_page/domain/usecases/get_exam_questions_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:exam_app/core/config/base_response/base_response.dart' as _i3;
import 'package:exam_app/features/exams_page/data/datasources/get_exam_questions_remote_datasource.dart'
    as _i2;
import 'package:exam_app/features/exams_page/data/repos/get_exam_questions_repo_impl.dart'
    as _i4;
import 'package:exam_app/features/exams_page/domain/models/question_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetExamQuestionsRemoteDatasource_0 extends _i1.SmartFake
    implements _i2.GetExamQuestionsRemoteDatasource {
  _FakeGetExamQuestionsRemoteDatasource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeBaseResponse_1<T> extends _i1.SmartFake
    implements _i3.BaseResponse<T> {
  _FakeBaseResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetExamQuestionsRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExamQuestionsRepoImpl extends _i1.Mock
    implements _i4.GetExamQuestionsRepoImpl {
  MockGetExamQuestionsRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetExamQuestionsRemoteDatasource get getExamQuestionsRemoteDatasourse =>
      (super.noSuchMethod(
            Invocation.getter(#getExamQuestionsRemoteDatasourse),
            returnValue: _FakeGetExamQuestionsRemoteDatasource_0(
              this,
              Invocation.getter(#getExamQuestionsRemoteDatasourse),
            ),
          )
          as _i2.GetExamQuestionsRemoteDatasource);

  @override
  set getExamQuestionsRemoteDatasourse(
    _i2.GetExamQuestionsRemoteDatasource? _getExamQuestionsRemoteDatasourse,
  ) => super.noSuchMethod(
    Invocation.setter(
      #getExamQuestionsRemoteDatasourse,
      _getExamQuestionsRemoteDatasourse,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.BaseResponse<List<_i6.QuestionModel>>> getExamQuestions({
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExamQuestions, [], {#examId: examId}),
            returnValue:
                _i5.Future<_i3.BaseResponse<List<_i6.QuestionModel>>>.value(
                  _FakeBaseResponse_1<List<_i6.QuestionModel>>(
                    this,
                    Invocation.method(#getExamQuestions, [], {#examId: examId}),
                  ),
                ),
          )
          as _i5.Future<_i3.BaseResponse<List<_i6.QuestionModel>>>);
}
