// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/profile/data/repositories/profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:exam_app/features/profile/data/datasources/profile_remote_data_source.dart'
    as _i3;
import 'package:exam_app/features/profile/data/models/user_profile_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserProfileModel_0 extends _i1.SmartFake
    implements _i2.UserProfileModel {
  _FakeUserProfileModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i3.ProfileRemoteDataSource {
  @override
  _i4.Future<_i2.UserProfileModel> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i4.Future<_i2.UserProfileModel>.value(
              _FakeUserProfileModel_0(this, Invocation.method(#getProfile, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserProfileModel>.value(
              _FakeUserProfileModel_0(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i4.Future<_i2.UserProfileModel>);

  @override
  _i4.Future<String> editProfile({
    String? firstName,
    String? lastName,
    String? email,
    String? phone,
    String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phone: phone,
              #username: username,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#editProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #phone: phone,
                  #username: username,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#editProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #phone: phone,
                  #username: username,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> changePassword({
    required String? oldPassword,
    required String? newPassword,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#changePassword, [], {
                  #oldPassword: oldPassword,
                  #newPassword: newPassword,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#changePassword, [], {
                  #oldPassword: oldPassword,
                  #newPassword: newPassword,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}
