// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/signup/data/repositories/signup_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:exam_app/features/signup/data/datasources/signup_remote_data_source.dart'
    as _i3;
import 'package:exam_app/features/signup/data/models/signup_response_model.dart'
    as _i2;
import 'package:exam_app/features/signup/domain/entities/signup_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignupResponseModel_0 extends _i1.SmartFake
    implements _i2.SignupResponseModel {
  _FakeSignupResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignupRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupRemoteDataSource extends _i1.Mock
    implements _i3.SignupRemoteDataSource {
  @override
  _i4.Future<_i2.SignupResponseModel> signup(_i5.SignupEntity? entity) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [entity]),
            returnValue: _i4.Future<_i2.SignupResponseModel>.value(
              _FakeSignupResponseModel_0(
                this,
                Invocation.method(#signup, [entity]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.SignupResponseModel>.value(
                  _FakeSignupResponseModel_0(
                    this,
                    Invocation.method(#signup, [entity]),
                  ),
                ),
          )
          as _i4.Future<_i2.SignupResponseModel>);
}
