// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/auth/data/repositories/signup_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dio/dio.dart' as _i3;
import 'package:exam_app/core/config/base_response/base_response.dart' as _i4;
import 'package:exam_app/features/auth/api/clients/auth_api_client.dart' as _i2;
import 'package:exam_app/features/auth/api/data_source/auth_local_datasource_impl.dart'
    as _i14;
import 'package:exam_app/features/auth/api/data_source/auth_remote_datasource_impl.dart'
    as _i7;
import 'package:exam_app/features/auth/data/models/login_dto.dart' as _i9;
import 'package:exam_app/features/auth/data/models/reset_password_response.dart'
    as _i12;
import 'package:exam_app/features/auth/data/models/send_reset_code_response.dart'
    as _i10;
import 'package:exam_app/features/auth/data/models/signup_response_model.dart'
    as _i5;
import 'package:exam_app/features/auth/data/models/verify_reset_code_response.dart'
    as _i11;
import 'package:exam_app/features/auth/domain/models/signup_entity.dart'
    as _i13;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthApiClient_0 extends _i1.SmartFake implements _i2.AuthApiClient {
  _FakeAuthApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseResponse_2<T> extends _i1.SmartFake
    implements _i4.BaseResponse<T> {
  _FakeBaseResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignupResponseModel_3 extends _i1.SmartFake
    implements _i5.SignupResponseModel {
  _FakeSignupResponseModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterSecureStorage_4 extends _i1.SmartFake
    implements _i6.FlutterSecureStorage {
  _FakeFlutterSecureStorage_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasourceImpl extends _i1.Mock
    implements _i7.AuthRemoteDatasourceImpl {
  MockAuthRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthApiClient get authApiClient =>
      (super.noSuchMethod(
            Invocation.getter(#authApiClient),
            returnValue: _FakeAuthApiClient_0(
              this,
              Invocation.getter(#authApiClient),
            ),
          )
          as _i2.AuthApiClient);

  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_1(this, Invocation.getter(#dio)),
          )
          as _i3.Dio);

  @override
  set authApiClient(_i2.AuthApiClient? _authApiClient) => super.noSuchMethod(
    Invocation.setter(#authApiClient, _authApiClient),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i4.BaseResponse<_i9.LoginDto>> login({
    String? email,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i8.Future<_i4.BaseResponse<_i9.LoginDto>>.value(
              _FakeBaseResponse_2<_i9.LoginDto>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.BaseResponse<_i9.LoginDto>>);

  @override
  _i8.Future<_i4.BaseResponse<_i10.SendResetCodeResponse>> sendResetCode(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetCode, [email]),
            returnValue:
                _i8.Future<_i4.BaseResponse<_i10.SendResetCodeResponse>>.value(
                  _FakeBaseResponse_2<_i10.SendResetCodeResponse>(
                    this,
                    Invocation.method(#sendResetCode, [email]),
                  ),
                ),
          )
          as _i8.Future<_i4.BaseResponse<_i10.SendResetCodeResponse>>);

  @override
  _i8.Future<_i4.BaseResponse<_i11.VerifyResetCodeResponse>> verifyResetCode(
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [code]),
            returnValue:
                _i8.Future<
                  _i4.BaseResponse<_i11.VerifyResetCodeResponse>
                >.value(
                  _FakeBaseResponse_2<_i11.VerifyResetCodeResponse>(
                    this,
                    Invocation.method(#verifyResetCode, [code]),
                  ),
                ),
          )
          as _i8.Future<_i4.BaseResponse<_i11.VerifyResetCodeResponse>>);

  @override
  _i8.Future<_i4.BaseResponse<_i12.ResetPasswordResponse>> resetPassword(
    String? email,
    String? passowrd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email, passowrd]),
            returnValue:
                _i8.Future<_i4.BaseResponse<_i12.ResetPasswordResponse>>.value(
                  _FakeBaseResponse_2<_i12.ResetPasswordResponse>(
                    this,
                    Invocation.method(#resetPassword, [email, passowrd]),
                  ),
                ),
          )
          as _i8.Future<_i4.BaseResponse<_i12.ResetPasswordResponse>>);

  @override
  _i8.Future<_i5.SignupResponseModel> signup(_i13.SignupEntity? entity) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [entity]),
            returnValue: _i8.Future<_i5.SignupResponseModel>.value(
              _FakeSignupResponseModel_3(
                this,
                Invocation.method(#signup, [entity]),
              ),
            ),
          )
          as _i8.Future<_i5.SignupResponseModel>);
}

/// A class which mocks [AuthLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDatasourceImpl extends _i1.Mock
    implements _i14.AuthLocalDatasourceImpl {
  MockAuthLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.FlutterSecureStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeFlutterSecureStorage_4(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i6.FlutterSecureStorage);

  @override
  set secureStorage(_i6.FlutterSecureStorage? _secureStorage) =>
      super.noSuchMethod(
        Invocation.setter(#secureStorage, _secureStorage),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveRememberMe, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
