// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/profile/domain/usecases/get_profile_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:exam_app/features/profile/domain/entities/user_profile_entity.dart'
    as _i4;
import 'package:exam_app/features/profile/domain/repositories/profile_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  @override
  _i3.Future<_i4.UserProfileEntity?> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i3.Future<_i4.UserProfileEntity?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i4.UserProfileEntity?>.value(),
          )
          as _i3.Future<_i4.UserProfileEntity?>);

  @override
  _i3.Future<String> editProfile({
    String? firstName,
    String? lastName,
    String? email,
    String? phone,
    String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phone: phone,
              #username: username,
            }),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#editProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #phone: phone,
                  #username: username,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#editProfile, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #phone: phone,
                  #username: username,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> changePassword({
    required String? oldPassword,
    required String? newPassword,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#changePassword, [], {
                  #oldPassword: oldPassword,
                  #newPassword: newPassword,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#changePassword, [], {
                  #oldPassword: oldPassword,
                  #newPassword: newPassword,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
          )
          as _i3.Future<String>);
}
