// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/auth/domain/usecases/signup_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dartz/dartz.dart' as _i6;
import 'package:exam_app/core/config/base_response/base_response.dart' as _i5;
import 'package:exam_app/core/config/error/error_handler.dart' as _i12;
import 'package:exam_app/features/auth/data/data_source/auth_local_datasource.dart'
    as _i4;
import 'package:exam_app/features/auth/data/data_source/auth_remote_datasource.dart'
    as _i3;
import 'package:exam_app/features/auth/data/models/reset_password_response.dart'
    as _i10;
import 'package:exam_app/features/auth/data/models/send_reset_code_response.dart'
    as _i11;
import 'package:exam_app/features/auth/data/models/verify_reset_code_response.dart'
    as _i15;
import 'package:exam_app/features/auth/data/repositories/auth_repo_impl.dart'
    as _i7;
import 'package:exam_app/features/auth/domain/models/login_model.dart' as _i9;
import 'package:exam_app/features/auth/domain/models/signup_entity.dart'
    as _i14;
import 'package:exam_app/features/auth/domain/models/signup_result_entity.dart'
    as _i13;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRemoteDatasource_1 extends _i1.SmartFake
    implements _i3.AuthRemoteDatasource {
  _FakeAuthRemoteDatasource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthLocalDatasource_2 extends _i1.SmartFake
    implements _i4.AuthLocalDatasource {
  _FakeAuthLocalDatasource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseResponse_3<T> extends _i1.SmartFake
    implements _i5.BaseResponse<T> {
  _FakeBaseResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_4<L, R> extends _i1.SmartFake implements _i6.Either<L, R> {
  _FakeEither_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepoImpl extends _i1.Mock implements _i7.AuthRepoImpl {
  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
            returnValueForMissingStub: _FakeLogger_0(
              this,
              Invocation.getter(#logger),
            ),
          )
          as _i2.Logger);

  @override
  _i3.AuthRemoteDatasource get authRemoteDatasource =>
      (super.noSuchMethod(
            Invocation.getter(#authRemoteDatasource),
            returnValue: _FakeAuthRemoteDatasource_1(
              this,
              Invocation.getter(#authRemoteDatasource),
            ),
            returnValueForMissingStub: _FakeAuthRemoteDatasource_1(
              this,
              Invocation.getter(#authRemoteDatasource),
            ),
          )
          as _i3.AuthRemoteDatasource);

  @override
  _i4.AuthLocalDatasource get authLocalDatasource =>
      (super.noSuchMethod(
            Invocation.getter(#authLocalDatasource),
            returnValue: _FakeAuthLocalDatasource_2(
              this,
              Invocation.getter(#authLocalDatasource),
            ),
            returnValueForMissingStub: _FakeAuthLocalDatasource_2(
              this,
              Invocation.getter(#authLocalDatasource),
            ),
          )
          as _i4.AuthLocalDatasource);

  @override
  _i8.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i5.BaseResponse<_i9.LoginModel>> login({
    String? email,
    String? password,
    bool? rememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #email: email,
              #password: password,
              #rememberMe: rememberMe,
            }),
            returnValue: _i8.Future<_i5.BaseResponse<_i9.LoginModel>>.value(
              _FakeBaseResponse_3<_i9.LoginModel>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                  #rememberMe: rememberMe,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i5.BaseResponse<_i9.LoginModel>>.value(
                  _FakeBaseResponse_3<_i9.LoginModel>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                      #rememberMe: rememberMe,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i5.BaseResponse<_i9.LoginModel>>);

  @override
  _i8.Future<_i5.BaseResponse<_i10.ResetPasswordResponse>> resetPassword(
    String? email,
    String? passowrd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email, passowrd]),
            returnValue:
                _i8.Future<_i5.BaseResponse<_i10.ResetPasswordResponse>>.value(
                  _FakeBaseResponse_3<_i10.ResetPasswordResponse>(
                    this,
                    Invocation.method(#resetPassword, [email, passowrd]),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i5.BaseResponse<_i10.ResetPasswordResponse>>.value(
                  _FakeBaseResponse_3<_i10.ResetPasswordResponse>(
                    this,
                    Invocation.method(#resetPassword, [email, passowrd]),
                  ),
                ),
          )
          as _i8.Future<_i5.BaseResponse<_i10.ResetPasswordResponse>>);

  @override
  _i8.Future<void> saveRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveRememberMe, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.BaseResponse<_i11.SendResetCodeResponse>> sendResetCode(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetCode, [email]),
            returnValue:
                _i8.Future<_i5.BaseResponse<_i11.SendResetCodeResponse>>.value(
                  _FakeBaseResponse_3<_i11.SendResetCodeResponse>(
                    this,
                    Invocation.method(#sendResetCode, [email]),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<_i5.BaseResponse<_i11.SendResetCodeResponse>>.value(
                  _FakeBaseResponse_3<_i11.SendResetCodeResponse>(
                    this,
                    Invocation.method(#sendResetCode, [email]),
                  ),
                ),
          )
          as _i8.Future<_i5.BaseResponse<_i11.SendResetCodeResponse>>);

  @override
  _i8.Future<_i6.Either<_i12.Failure<dynamic>, _i13.SignupResultEntity>> signup(
    _i14.SignupEntity? signupEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [signupEntity]),
            returnValue:
                _i8.Future<
                  _i6.Either<_i12.Failure<dynamic>, _i13.SignupResultEntity>
                >.value(
                  _FakeEither_4<_i12.Failure<dynamic>, _i13.SignupResultEntity>(
                    this,
                    Invocation.method(#signup, [signupEntity]),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<
                  _i6.Either<_i12.Failure<dynamic>, _i13.SignupResultEntity>
                >.value(
                  _FakeEither_4<_i12.Failure<dynamic>, _i13.SignupResultEntity>(
                    this,
                    Invocation.method(#signup, [signupEntity]),
                  ),
                ),
          )
          as _i8.Future<
            _i6.Either<_i12.Failure<dynamic>, _i13.SignupResultEntity>
          >);

  @override
  _i8.Future<void> storeToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#storeToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.BaseResponse<_i15.VerifyResetCodeResponse>> verifyResetCode(
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [code]),
            returnValue:
                _i8.Future<
                  _i5.BaseResponse<_i15.VerifyResetCodeResponse>
                >.value(
                  _FakeBaseResponse_3<_i15.VerifyResetCodeResponse>(
                    this,
                    Invocation.method(#verifyResetCode, [code]),
                  ),
                ),
            returnValueForMissingStub:
                _i8.Future<
                  _i5.BaseResponse<_i15.VerifyResetCodeResponse>
                >.value(
                  _FakeBaseResponse_3<_i15.VerifyResetCodeResponse>(
                    this,
                    Invocation.method(#verifyResetCode, [code]),
                  ),
                ),
          )
          as _i8.Future<_i5.BaseResponse<_i15.VerifyResetCodeResponse>>);
}
