// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/exams_page/api/datasources/get_exam_questions_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:exam_app/features/exams_page/api/api_client/exam_questions_api_client.dart'
    as _i3;
import 'package:exam_app/features/exams_page/data/models/exam_questions_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExamQuestionsResponse_0 extends _i1.SmartFake
    implements _i2.ExamQuestionsResponse {
  _FakeExamQuestionsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExamQuestionsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamQuestionsApiClient extends _i1.Mock
    implements _i3.ExamQuestionsApiClient {
  MockExamQuestionsApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExamQuestionsResponse> getExamQuestions(String? examId) =>
      (super.noSuchMethod(
            Invocation.method(#getExamQuestions, [examId]),
            returnValue: _i4.Future<_i2.ExamQuestionsResponse>.value(
              _FakeExamQuestionsResponse_0(
                this,
                Invocation.method(#getExamQuestions, [examId]),
              ),
            ),
          )
          as _i4.Future<_i2.ExamQuestionsResponse>);
}
